### ISSUE TITLE
glowroot - requirement manually to set runAsUser / fsGroup

### ISSUE THREAD

**Issue by robinroos** [novumrgi/helm#11]
I'm using the NOVUM-RGI Helm Chart (v0.13.7) to deploy Glowroot (Central Collector) into OpenShift 4.6.

https://artifacthub.io/packages/helm/novum-rgi-charts/glowroot

After doing the helm install it was necessary to change the above values, part of the securityContext YML group, as the default values 1001 were invalid.  

Perhaps these could be parameterised and set at install time?

**Comment by luhahn** [comment]
added new value to configure securityContext. 

Note that there are two securityContexts, one for the container, one in general for the deployment

```yaml
securityContext:
 fsGroup: 999

glowroot:
# securityContext: Currently empty by default
```

**Comment by luhahn** [comment]
Still wonder why you get these errors, the glowroot chart is running with default values in my cluster

**Comment by robinroos** [comment]
My project has been configured with a userid range which doesn't include 1001:

```
> oc describe project <projectname>
...
openshift.io/sa.scc.supplemental-groups=1000550000/10000
openshift.io/sa.scc.uid-range=1000550000/10000
...
```

That is why I had to set runAsUser..

Presumably your project does permit user 1001 ?

**Comment by luhahn** [comment]
No, i just added 999 as default fsGroup. The rest of the permissions is up to the glowroot container.
However you should be able to configure that in version 1.0.5 of the glowroot chart :)

**Comment by robinroos** [comment]
Is 1.0.5 available now, and how would I pass my values for runAsUser and fsGroup in the heml install command?

So far I just use helm install - I do not define any .yaml fragments.

**Comment by luhahn** [comment]
Hey, sorry, yes 1.0.5 is available since yesterday, forgot to mention that.

You would simply create a yaml file containing the values, as for the fsGroup this would be:

```yaml
securityContext:
  fsGroup: 999
```

you can also use something like that:

```yaml
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
```

All available and parsed values can be found here: https://github.com/novumrgi/helm/blob/master/charts/glowroot/values.yaml

**Comment by robinroos** [comment]
Thanks.  I can attest that the runAsUser, runAsGroup and fsGroup were correctly populated in the Deployment "glowroot" from a .yml file when I installed version 1.0.5 of the glowroot helm chart.

The StatefulSet "glowroot-cassandra", a product of the imported bitnami helm chart, still had default values of 1001.

You may close this issue as resolved.
