### ISSUE TITLE
glowroot - requirement to recreate Persistent Volume Claim

### ISSUE THREAD

**Issue by robinroos** [novumrgi/helm#12]
I'm using the NOVUM-RGI Helm Chart (v0.13.7) to deploy Glowroot (Central Collector) into OpenShift 4.6.

https://artifacthub.io/packages/helm/novum-rgi-charts/glowroot

After doing the helm install the Persistent Volume Claim (PVC) referenced a non-existant Persistent Volume (PV) called data-glowroot-cassandra-0.

Since PVCs are immutable it was necessary to delete the original PCV and recreate it with the reference to a valid PV.

Could the name of the PV be parameterised in the helm chart so that the PVC can be correctly configured at installation time?

**Comment by luhahn** [comment]
The Cassandra volume will be created by the cassandra chart dependency from https://github.com/bitnami/charts/tree/master/bitnami/cassandra

I will add another parameter to the values

```yaml
cassandra:
  enabled: true
```
Which will be used to enable/disable the cassandra dependency, so an external DB can be used.

**Comment by robinroos** [comment]
Is is possible to parameterise the chart with a Persistent Volume name to be used by the imported bitnami Cassandra chart?

**Comment by luhahn** [comment]
Couldn't find any. 
Why is the default name not working for you? Are there any details when you describe the default cassandra pvc?

The dependency should create setup the PVC for the cassandra database.
