### ISSUE TITLE
Please provide collector  glowroot-0.14.0-beta.3 for java 17 compatibility

### ISSUE THREAD

**Issue by materemias** [novumrgi/helm#19]
we need glowroot 0.14 for java17 support, could you please publish such a collector docker image?
https://hub.docker.com/r/novumrgi/glowroot-central/tags

**Comment by robinroos** [comment]
@luhahn See also #16

**Comment by luhahn** [comment]
Hey, guys, I was rather busy with other projects, sorry it took so long to answer. I will start working on this topic today/tomorrow

**Comment by luhahn** [comment]
done in 1.0.8, docker images are updated. Also works with the old chart version.

**Comment by materemias** [comment]
confirmed working, thanks a lot!
