### ISSUE TITLE
Add support for configuring terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by onedr0p** [novumrgi/helm#2]
When the node a STS is running on fails the pod goes into a unknown or failed state, this should help it be evicted to another node.

Example:

https://github.com/vernemq/docker-vernemq/blob/master/helm/vernemq/templates/statefulset.yaml#L38

**Comment by luhahn** [comment]
Implemented in 4449b66f4c985772edf0ddad8afc1dab4841ce54
