### ISSUE TITLE
Glowroot Charts cannot be upgraded

### ISSUE THREAD

**Issue by haagtobias** [novumrgi/helm#21]
Hello,

I have encountered a problem while executing "helm upgrade" on the glowroot chart when it is already installed.
`Error: UPGRADE FAILED: cannot patch "glowroot-collector" with kind Service: Service "glowroot-collector" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset`

I think the problem is that after the first installation kubernetes is assigning IP addresses to the service and writes those into the clusterIPs field.

I think the clusterIPs should just be ommited in the service manifest and the problem will be solved.

Best regards,
Tobi

**Comment by luhahn** [comment]
can you try again with version 1.0.8. Please mind the breaking changes in ingress :)

**Comment by haagtobias** [comment]
Thanks for the fast response, but unfortunately it is still not working. I think you have to change the collector-svc.yaml. It was last changed in 2020.

**Comment by luhahn** [comment]
Okay, hopefully this time :). I totally missed the collector service

**Comment by luhahn** [comment]
I am sorry, yes I was aware of that and already had a fix. However I somehow forgot to push the changes, please try again with 1.0.10. Again sorry for the inconvinience

**Comment by haagtobias** [comment]
Now I get the original error message again:
UPGRADE FAILED: cannot patch "glowroot-collector" with kind Service: Service "glowroot-collector" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset

I think clusterIP should be completely omitted if the corresponding value is nil.

**Comment by luhahn** [comment]
correct me if I'm wrong, but the clusterIP should be omitted, if you're not setting: .Values.service.collector.clusterIP
or if the service type is something other than ClusterIP. At least thats what happening when I'm running helm template.

**Comment by haagtobias** [comment]
You are right, the problem was the old release. I did a helm uninstall once and now it is upgrading fine.
Thanks for the fix
