### ISSUE TITLE
Not possible to set imagePullSecret in Glowroot Chart

### ISSUE THREAD

**Issue by haagtobias** [novumrgi/helm#22]
Hello,

I would like to put a copy of the image into a private registry. Unfortunately it is currently not possible to add the name of the imagePullSecret to the deployment with helm install. This is possible with most other helm charts. Maybe you could support that, too?

Best regards,
Tobi

**Comment by robinroos** [comment]
This would also be useful in the furure if ever the images were moved to a registry which requires authentication, e.g. docker.io which now throttles pulls with anonymous access, and does so to the extent that it is unworkable without providing appropriate secrets.

**Comment by luhahn** [comment]
done in version 1.0.8
