### ISSUE TITLE
Gitea: Add support for prometheus metrics

### ISSUE THREAD

**Issue by onedr0p** [novumrgi/helm#3]
Including a servicemonitor would also be great for Prometheus Operator

Examples:

https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/templates/servicemonitor.yaml
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L509

**Comment by luhahn** [comment]
Gitea chart moved to gitea.com
